In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

df= pd.read_csv(r"autos.csv", encoding="ISO-8859-1")
df.head()

dateCrawled                            name  seller offerType  \
0  2016-03-24 11:52:17                      Golf_3_1.6  privat   Angebot   
1  2016-03-24 10:58:45            A5_Sportback_2.7_Tdi  privat   Angebot   
2  2016-03-14 12:52:21  Jeep_Grand_Cherokee_"Overland"  privat   Angebot   
3  2016-03-17 16:54:04              GOLF_4_1_4__3TÜRER  privat   Angebot   
4  2016-03-31 17:25:20  Skoda_Fabia_1.4_TDI_PD_Classic  privat   Angebot   

   price abtest vehicleType  yearOfRegistration    gearbox  powerPS  model  \
0    480   test         NaN                1993    manuell        0   golf   
1  18300   test       coupe                2011    manuell      190    NaN   
2   9800   test         suv                2004  automatik      163  grand   
3   1500   test  kleinwagen                2001    manuell       75   golf   
4   3600   test  kleinwagen                2008    manuell       69  fabia   

   kilometer  monthOfRegistration fuelType       brand notRepairedDamage  \
0     150000                    0   benzin  volkswagen               NaN   
1     125000                    5   diesel        audi                ja   
2     125000                    8   diesel        jeep               NaN   
3     150000                    6   benzin  volkswagen              nein   
4      90000                    7   diesel       skoda              nein   

           dateCreated  nrOfPictures  postalCode             lastSeen  
0  2016-03-24 00:00:00             0       70435  2016-04-07 03:16:57  
1  2016-03-24 00:00:00             0       66954  2016-04-07 01:46:50  
2  2016-03-14 00:00:00             0       90480  2016-04-05 12:47:46  
3  2016-03-17 00:00:00             0       91074  2016-03-17 17:40:17  
4  2016-03-31 00:00:00             0       60437  2016-04-06 10:17:21

In [2]:
df.shape

(371528, 20)

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 20 columns):
dateCrawled            371528 non-null object
name                   371528 non-null object
seller                 371528 non-null object
offerType              371528 non-null object
price                  371528 non-null int64
abtest                 371528 non-null object
vehicleType            333659 non-null object
yearOfRegistration     371528 non-null int64
gearbox                351319 non-null object
powerPS                371528 non-null int64
model                  351044 non-null object
kilometer              371528 non-null int64
monthOfRegistration    371528 non-null int64
fuelType               338142 non-null object
brand                  371528 non-null object
notRepairedDamage      299468 non-null object
dateCreated            371528 non-null object
nrOfPictures           371528 non-null int64
postalCode             371528 non-null int64
lastSeen              

price  yearOfRegistration        powerPS      kilometer  \
count  3.715280e+05       371528.000000  371528.000000  371528.000000   
mean   1.729514e+04         2004.577997     115.549477  125618.688228   
std    3.587954e+06           92.866598     192.139578   40112.337051   
min    0.000000e+00         1000.000000       0.000000    5000.000000   
25%    1.150000e+03         1999.000000      70.000000  125000.000000   
50%    2.950000e+03         2003.000000     105.000000  150000.000000   
75%    7.200000e+03         2008.000000     150.000000  150000.000000   
max    2.147484e+09         9999.000000   20000.000000  150000.000000   

       monthOfRegistration  nrOfPictures    postalCode  
count        371528.000000      371528.0  371528.00000  
mean              5.734445           0.0   50820.66764  
std               3.712412           0.0   25799.08247  
min               0.000000           0.0    1067.00000  
25%               3.000000           0.0   30459.00000  
50%               6.000000           0.0   49610.00000  
75%               9.000000           0.0   71546.00000  
max              12.000000           0.0   99998.00000

Data Analysis

In [4]:
df.isnull().sum()

dateCrawled                0
name                       0
seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [5]:
df["offerType"].value_counts()
#.unique()

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64

In [6]:
df["seller"].value_counts()

privat        371525
gewerblich         3
Name: seller, dtype: int64

In [7]:
df["abtest"].value_counts()
#.unique()

test       192585
control    178943
Name: abtest, dtype: int64

In [8]:
df["vehicleType"].value_counts().unique()

array([95894, 80023, 67564, 30201, 22898, 19015, 14707,  3357],
      dtype=int64)

In [9]:
df["yearOfRegistration"].value_counts().unique()

array([24551, 22767, 22316, 20230, 20218, 19873, 19746, 19189, 17951,
       17673, 16175, 15607, 14706, 12354, 12068, 10886, 10546,  9859,
        9658,  9418,  6157,  4872,  4802,  3993,  3469,  3048,  2982,
        2852,  2810,  1342,   965,   787,   697,   629,   576,   455,
         422,   370,   335,   312,   307,   284,   248,   214,   205,
         201,   199,   193,   160,   154,   152,   147,   142,   121,
         104,    80,    77,    53,    51,    45,    38,    34,    33,
          27,    25,    22,    19,    18,    16,    13,    12,     8,
           7,     6,     5,     4,     3,     2,     1], dtype=int64)

In [10]:
df["gearbox"].value_counts().unique()

array([274214,  77105], dtype=int64)

In [11]:
df["powerPS"].value_counts().unique()

array([40820, 24035, 15907, 15442, 13585, 13313, 12748, 11963, 10982,
       10429,  7051,  6952,  6500,  6287,  5752,  5547,  5322,  5179,
        4862,  4817,  4661,  4050,  3914,  3886,  3855,  3655,  3332,
        3023,  2991,  2828,  2729,  2713,  2635,  2567,  2506,  2462,
        2408,  2315,  2310,  2267,  2221,  2193,  2113,  1719,  1600,
        1570,  1525,  1514,  1495,  1448,  1399,  1365,  1292,  1250,
        1197,  1191,  1134,  1131,  1090,  1051,  1032,  1021,   989,
         988,   977,   974,   962,   949,   939,   931,   921,   920,
         898,   865,   814,   809,   806,   786,   767,   736,   726,
         723,   694,   657,   644,   610,   599,   551,   535,   532,
         500,   492,   454,   453,   446,   442,   441,   433,   420,
         415,   407,   404,   397,   390,   375,   373,   354,   335,
         326,   323,   321,   291,   288,   284,   276,   274,   273,
         271,   259,   255,   248,   234,   233,   225,   222,   215,
         212,   211,

In [12]:
df["model"].value_counts().unique()

array([30070, 26400, 20567, 13092, 12573, 10830, 10306, 10257,  8775,
        8546,  7561,  6604,  6023,  5950,  5775,  5528,  4953,  4816,
        4338,  4316,  4255,  3837,  3626,  3553,  3540,  3503,  3349,
        3049,  2927,  2702,  2594,  2307,  2195,  2124,  2080,  1854,
        1758,  1648,  1606,  1556,  1447,  1417,  1386,  1374,  1364,
        1350,  1325,  1306,  1291,  1253,  1168,  1147,  1143,  1052,
        1034,  1032,  1020,  1018,   958,   954,   937,   927,   916,
         914,   910,   902,   899,   890,   872,   869,   859,   825,
         793,   789,   782,   764,   745,   744,   706,   699,   694,
         685,   676,   670,   669,   645,   640,   638,   629,   622,
         621,   620,   609,   603,   584,   582,   572,   567,   549,
         536,   506,   493,   471,   457,   451,   449,   447,   444,
         437,   430,   423,   422,   419,   417,   414,   409,   404,
         401,   399,   396,   395,   391,   388,   386,   379,   377,
         374,   373,

In [13]:
df["kilometer"].value_counts().unique()

array([240797,  38067,  15920,  12523,  11053,   9773,   8669,   7615,
         7069,   6376,   6041,   5676,   1949], dtype=int64)

In [14]:
df["monthOfRegistration"].value_counts().unique()

array([37675, 36170, 33167, 30918, 30631, 28958, 27337, 25489, 25380,
       25074, 24561, 23765, 22403], dtype=int64)

In [15]:
df["fuelType"].value_counts().unique()

array([223857, 107746,   5378,    571,    278,    208,    104],
      dtype=int64)

In [16]:
df["brand"].value_counts().unique()

array([79640, 40274, 40136, 35309, 32873, 25573, 17969, 11027,  9676,
        7022,  5695,  5641,  5249,  5182,  5037,  4694,  3982,  3646,
        3394,  3327,  3061,  2836,  2555,  2345,  2328,  2215,  1845,
        1452,   900,   807,   806,   779,   770,   621,   591,   542,
         530,   490,   484,   225], dtype=int64)

In [17]:
df["notRepairedDamage"].value_counts()
# .unique()

nein    263182
ja       36286
Name: notRepairedDamage, dtype: int64

In [18]:
df["dateCreated"].value_counts().unique()

array([14450, 14022, 13547, 13379, 13305, 13088, 13069, 12991, 12821,
       12752, 12723, 12714, 12623, 12402, 12399, 12396, 12264, 12181,
       12050, 11958, 11920, 11872, 11856, 11610, 11285, 11161, 11132,
        8528,  6318,  5752,  5215,  4330,  1172,   630,   579,   415,
          53,    51,    50,    42,    24,    23,    22,    21,    14,
          13,    12,     9,     8,     7,     6,     5,     4,     3,
           2,     1], dtype=int64)

In [19]:
df["nrOfPictures"].value_counts()
# .unique() delete

0    371528
Name: nrOfPictures, dtype: int64

In [20]:
df["postalCode"].value_counts().unique()

array([828, 637, 349, 326, 323, 314, 309, 301, 294, 293, 284, 283, 282,
       281, 278, 277, 275, 269, 266, 265, 262, 261, 257, 254, 251, 250,
       247, 246, 245, 244, 243, 242, 241, 240, 239, 238, 237, 236, 235,
       234, 232, 231, 230, 229, 228, 227, 225, 224, 223, 222, 221, 220,
       219, 218, 217, 216, 215, 214, 213, 212, 211, 210, 209, 208, 207,
       206, 205, 203, 202, 201, 200, 199, 198, 197, 196, 195, 194, 193,
       191, 190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 179,
       178, 177, 176, 175, 174, 173, 172, 171, 170, 169, 168, 167, 166,
       165, 164, 163, 162, 161, 160, 159, 158, 157, 156, 155, 154, 153,
       152, 151, 150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140,
       139, 138, 137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127,
       126, 125, 124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114,
       113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101,
       100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  8

In [21]:
df["lastSeen"].value_counts().unique()

array([17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
      dtype=int64)

In [22]:
"""we should delete nrOfPictures

"""

'we should delete nrOfPictures\n\n'

In [23]:
df["name"].value_counts().unique()

array([657, 627, 622, 603, 523, 492, 475, 447, 428, 413, 412, 394, 373,
       369, 366, 365, 361, 344, 322, 274, 273, 260, 254, 245, 242, 241,
       238, 233, 226, 225, 219, 215, 211, 209, 206, 203, 200, 198, 194,
       187, 185, 181, 174, 173, 172, 168, 166, 164, 163, 162, 159, 155,
       153, 152, 150, 148, 145, 143, 142, 139, 138, 136, 134, 132, 131,
       130, 129, 127, 126, 124, 123, 122, 121, 119, 118, 117, 116, 115,
       114, 113, 112, 111, 110, 108, 107, 106, 102, 101, 100,  99,  98,
        97,  96,  95,  93,  92,  91,  89,  88,  87,  86,  85,  84,  83,
        82,  81,  80,  79,  78,  77,  76,  75,  74,  73,  72,  71,  70,
        69,  68,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,  57,
        56,  55,  54,  53,  52,  51,  50,  49,  48,  47,  46,  45,  44,
        43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,  32,  31,
        30,  29,  28,  27,  26,  25,  24,  23,  22,  21,  20,  19,  18,
        17,  16,  15,  14,  13,  12,  11,  10,   9,   8,   7,   

Deleting unwanted columns

In [24]:
del df["name"]

In [25]:
df.drop(["dateCrawled","lastSeen","dateCreated","nrOfPictures"],axis="columns",inplace=True)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 15 columns):
seller                 371528 non-null object
offerType              371528 non-null object
price                  371528 non-null int64
abtest                 371528 non-null object
vehicleType            333659 non-null object
yearOfRegistration     371528 non-null int64
gearbox                351319 non-null object
powerPS                371528 non-null int64
model                  351044 non-null object
kilometer              371528 non-null int64
monthOfRegistration    371528 non-null int64
fuelType               338142 non-null object
brand                  371528 non-null object
notRepairedDamage      299468 non-null object
postalCode             371528 non-null int64
dtypes: int64(6), object(9)
memory usage: 42.5+ MB


In [27]:
df.isnull().sum()

seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
postalCode                 0
dtype: int64

In [28]:
df["notRepairedDamage"].fillna("nein",inplace=True)

Filling NaN in vehicleType, gearbox, model, fuelType, notRepairedDamage

In [29]:
# df = df.dropna(how='any')
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 15 columns):
seller                 371528 non-null object
offerType              371528 non-null object
price                  371528 non-null int64
abtest                 371528 non-null object
vehicleType            333659 non-null object
yearOfRegistration     371528 non-null int64
gearbox                351319 non-null object
powerPS                371528 non-null int64
model                  351044 non-null object
kilometer              371528 non-null int64
monthOfRegistration    371528 non-null int64
fuelType               338142 non-null object
brand                  371528 non-null object
notRepairedDamage      371528 non-null object
postalCode             371528 non-null int64
dtypes: int64(6), object(9)
memory usage: 42.5+ MB


In [30]:
# df["seller"].value_counts()
df["seller"].replace(["privat","gewerblich"],[1,0],inplace=True)

In [31]:
# df["offerType"].value_counts()
df["offerType"].replace(["Angebot","Gesuch"],[1,0],inplace=True)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 15 columns):
seller                 371528 non-null int64
offerType              371528 non-null int64
price                  371528 non-null int64
abtest                 371528 non-null object
vehicleType            333659 non-null object
yearOfRegistration     371528 non-null int64
gearbox                351319 non-null object
powerPS                371528 non-null int64
model                  351044 non-null object
kilometer              371528 non-null int64
monthOfRegistration    371528 non-null int64
fuelType               338142 non-null object
brand                  371528 non-null object
notRepairedDamage      371528 non-null object
postalCode             371528 non-null int64
dtypes: int64(8), object(7)
memory usage: 42.5+ MB


In [33]:
from sklearn.preprocessing import LabelEncoder
df["vehicleType"] =LabelEncoder().fit_transform(df["vehicleType"].astype(str))
df["fuelType"] =LabelEncoder().fit_transform(df["fuelType"].astype(str))
df["gearbox"] =LabelEncoder().fit_transform(df["gearbox"].astype(str))
df["notRepairedDamage"] =LabelEncoder().fit_transform(df["notRepairedDamage"].astype(str))
df["brand"] =LabelEncoder().fit_transform(df["brand"].astype(str))
df["model"] =LabelEncoder().fit_transform(df["model"].astype(str))
df["abtest"] =LabelEncoder().fit_transform(df["abtest"].astype(str))

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 15 columns):
seller                 371528 non-null int64
offerType              371528 non-null int64
price                  371528 non-null int64
abtest                 371528 non-null int64
vehicleType            371528 non-null int64
yearOfRegistration     371528 non-null int64
gearbox                371528 non-null int64
powerPS                371528 non-null int64
model                  371528 non-null int64
kilometer              371528 non-null int64
monthOfRegistration    371528 non-null int64
fuelType               371528 non-null int64
brand                  371528 non-null int64
notRepairedDamage      371528 non-null int64
postalCode             371528 non-null int64
dtypes: int64(15)
memory usage: 42.5 MB


In [35]:
df[df.yearOfRegistration > 2017].shape

(4134, 15)

In [36]:
df[df.yearOfRegistration < 2019].shape

(371387, 15)

In [37]:
df = df[(df.yearOfRegistration < 2017)  & (df.yearOfRegistration > 1950)]

In [38]:
df[df.price < 100].shape

(12372, 15)

In [39]:
df[df.price > 200000].shape

(158, 15)

In [40]:
df = df[(df.price > 100) & (df.price < 200000) ]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 342990 entries, 0 to 371527
Data columns (total 15 columns):
seller                 342990 non-null int64
offerType              342990 non-null int64
price                  342990 non-null int64
abtest                 342990 non-null int64
vehicleType            342990 non-null int64
yearOfRegistration     342990 non-null int64
gearbox                342990 non-null int64
powerPS                342990 non-null int64
model                  342990 non-null int64
kilometer              342990 non-null int64
monthOfRegistration    342990 non-null int64
fuelType               342990 non-null int64
brand                  342990 non-null int64
notRepairedDamage      342990 non-null int64
postalCode             342990 non-null int64
dtypes: int64(15)
memory usage: 41.9 MB


In [42]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

y=df["price"]
X=df.drop(["price"],axis='columns')


In [43]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

X=sc.fit_transform(X)

In [44]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.02)

# model=RandomForestRegressor()
model=XGBRegressor()
model.fit(X_train, y_train)
# model.score(X_test,y_test)
pred=model.predict(X_test)
# print(y_test)
# print(pred)
from sklearn.metrics import r2_score
r2_score(y_test,pred)

0.868073680135516

In [45]:
# from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

# random_grid = {'eta': [x for x in np.linspace(start=0.01, stop=0.2, num = 4)],
#                'min_child_weight ': [int(x) for x in np.linspace(start=1, stop=11, num = 4)],
#                'max_depth ': [int(x) for x in np.linspace(start=3, stop=10, num = 4)],
#                'gamma': [int(x) for x in np.linspace(start=0, stop=10, num = 4)],
#                'subsample': [x for x in np.linspace(start=0.5, stop=1, num = 4)]}
# rf_random = RandomizedSearchCV(estimator = model, param_distributions = random_grid, cv = 3)
# # rf_random = GridSearchCV(model, random_grid, cv=4)
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2)
# rf_random.fit(X_train, y_train)
# rf_random.best_params_

In [ ]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
import numpy as np
n_estimators = [int(x) for x in np.linspace(start=1, stop=100, num = 20)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(1, 50, num = 11)]
max_depth.append(None)
min_samples_split = [2, 3, 5, 10, 12, 15, 20]
min_samples_leaf = [1, 2, 4,6,8,10]
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
rf_random = RandomizedSearchCV(estimator = model, param_distributions = random_grid, cv = 4)
# rf_random = GridSearchCV(model, random_grid, cv=5)
rf_random.fit(X_train, y_train)
print(rf_random.best_score_)
rf_random.best_params_

In [ ]:
# {'n_estimators': 89,
#  'min_samples_split': 3,
#  'min_samples_leaf': 4,
#  'max_features': 'sqrt',
#  'max_depth': 35,
#  'bootstrap': False}
# model = RandomForestRegressor(n_estimators=89, min_samples_split=3, min_samples_leaf=4, max_features="sqrt", max_depth=35, bootstrap=False)
model = XGBRegressor(**rf_random.best_params_)
model.fit(X_train, y_train)

pred=model.predict(X_test)
# print(y_test)
# print(pred)
from sklearn.metrics import r2_score
print(r2_score(y_test, pred))
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,pred)